---
title: "LDA Tutorial"
author: "Chris Tufts"
bibliography:
- books.bib
- packages.bib
output:
  bookdown::pdf_book:
    latex_engine: xelatex
  bookdown::gitbook: 
    split_bib: no
link-citations: true
documentclass: book
site: bookdown::bookdown_site
biblio-style: apalike
twitter-handle: devlintufts
---

# Preface {-}

DISCLAIMER: THIS BOOK IS NOT COMPLETE (WORK IN PROGRESS):

* Please note this is a work in progress and is only being made available for viewing to provide an overview of the project.
* Please do not share.

The purpose of this book is to provide a step by step guide of LDA utilizing Gibbs Sampling.  It is
heavily inspired by the Gregor Heinrich's _Parameter Estimation for Text Analysis_[@heinrich2008parameter]. 

# Background {-}
I've often found that resources covering LDA are either hard to follow, do to a heavy reliance on calculus derivations, or the resources are extremely high level so you get the idea of what LDA accomplishes, but you never fully grasp how it works. The book focuses on LDA for inference via Gibbs Sampling. To aid in understanding both LDA and Gibbs sampling all probability distributions used in LDA will be reviewed along with a variety of different approaches for parameter estimation. Following the introduction of these components, LDA will be presented as a generative model.  This will lay the groundwork for understanding how LDA can be used for inference of topics in a corpus.  

I have tried my best to relay an explanation of LDA that fills in the gaps and questions that are sometimes left out of publications. The book contains many code examples, but I do not shy away from walking through mathematical derivations. Where applicable I state mathematical properties used in the derivations so that the reader doesn't have to 'take my word for it', but instead can go from A to B on their own.  You will find code examples written in R in the case you would like to try them out at home. I will warn you that my implmentation of LDA is not optimized and if you are doing analysis for any reason other than trying to learn I would suggest using one of the many great peices of open source software available - Mallet, Gensim, LDA(R), tidytext?, scikit? etc. ADD LINKS FOR THESE OR ADD APPENDIX WITH THESE TOOLS AND COMPARISON NOTES (I.E WHAT LANGUAGE, ETC.)

# Layout of Book {-}

* What is LDA? - High level overview
* Parameter Estimation Methods (general overview using Bernoulli distribution) - ML, MAP, Bayesian Inference, Gibbs Sampling
* Multinomial Distribution - Explains the relationship of Bernoulli to Multinomial, then goes into Gibbs Sampling 
* Word/Document Structures - Bag of Words, Word Document Matrix
* LDA - A Generative Model
* LDA - Inference

# Package References {-}
This book only came together due to the amazing open source work so many have done in the R community. The list of packages utilized to create this book can be found in the reference section and are as follows:
[@R-base], [@R-bindrcpp], [@R-bookdown], [@R-coda], [@R-dplyr], [@R-ggplot2], [@R-kableExtra], [@R-knitr],[@R-lsa], [@R-MASS], [@R-MCMCpack], [@R-purrr], [@R-Rcpp], [@R-readr], [@R-SnowballC],[@R-tibble], [@R-tidyr], [@R-tidyverse] 
